=== bobby-brennan/PayPal/schemas/agreementReq-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "start_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "plan" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "id" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "payer" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "payment_method" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "shipping_address" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "line1" : {
          "type" : "string" ,
          "required" : false
        } ,
        "line2" : {
          "type" : "string" ,
          "required" : false
        } ,
        "city" : {
          "type" : "string" ,
          "required" : false
        } ,
        "state" : {
          "type" : "string" ,
          "required" : false
        } ,
        "postal_code" : {
          "type" : "string" ,
          "required" : false
        } ,
        "country_code" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  }
}

=== bobby-brennan/PayPal/examples/agreementReq-example.json
{
  "description" : "Agreement for Fast Speed Plan" ,
  "start_date" : "2015-02-19T00:37:04Z" ,
  "plan" : {
    "id" : "P-0NJ10521L3680291SOAQIVTQ"
  } ,
  "payer" : {
    "payment_method" : "paypal"
  } ,
  "shipping_address" : {
    "line1" : "StayBridge Suites" ,
    "line2" : "Crok Street" ,
    "city" : "San Jose" ,
    "state" : "CA" ,
    "postal_code" : "95112" ,
    "country_code" : "US"
  }
}
