=== bobby-brennan/PayPal/schemas/creditCard-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "valid_until" : {
      "type" : "string" ,
      "required" : false
    } ,
    "state" : {
      "type" : "string" ,
      "required" : false
    } ,
    "payer_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "number" : {
      "type" : "string" ,
      "required" : false
    } ,
    "expire_month" : {
      "type" : "string" ,
      "required" : false
    } ,
    "expire_year" : {
      "type" : "string" ,
      "required" : false
    } ,
    "first_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "last_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "links" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "href" : {
              "type" : "string" ,
              "required" : false
            } ,
            "rel" : {
              "type" : "string" ,
              "required" : false
            } ,
            "method" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== bobby-brennan/PayPal/examples/creditCard-example.json
{
  "id" : "CARD-1MD19612EW4364010KGFNJQI" ,
  "valid_until" : "2016-05-07T00:00:00Z" ,
  "state" : "ok" ,
  "payer_id" : "user12345" ,
  "type" : "visa" ,
  "number" : "xxxxxxxxxxxx0331" ,
  "expire_month" : "11" ,
  "expire_year" : "2018" ,
  "first_name" : "Betsy" ,
  "last_name" : "Buyer" ,
  "links" : [
    {
      "href" : "https://api.sandbox.paypal.com/v1/vault/credit-card/CARD-1MD19612EW4364010KGFNJQI" ,
      "rel" : "self" ,
      "method" : "GET"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/vault/credit-card/CARD-1MD19612EW4364010KGFNJQI" ,
      "rel" : "delete" ,
      "method" : "DELETE"
    }
  ]
}
