=== bobby-brennan/PayPal/schemas/plan-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "state" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "payee" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "merchant_id" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "payment_definitions" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "frequency" : {
              "type" : "string" ,
              "required" : false
            } ,
            "frequency_interval" : {
              "type" : "string" ,
              "required" : false
            } ,
            "amount" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "currency" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "value" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "cycles" : {
              "type" : "string" ,
              "required" : false
            } ,
            "charge_models" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "id" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "type" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "amount" : {
                      "type" : "object" ,
                      "required" : false ,
                      "properties" : {
                        "currency" : {
                          "type" : "string" ,
                          "required" : false
                        } ,
                        "value" : {
                          "type" : "string" ,
                          "required" : false
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    } ,
    "merchant_preferences" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "setup_fee" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "currency" : {
              "type" : "string" ,
              "required" : false
            } ,
            "value" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "auto_bill_amount" : {
          "type" : "string" ,
          "required" : false
        } ,
        "initial_fail_amount_action" : {
          "type" : "string" ,
          "required" : false
        } ,
        "max_fail_attempts" : {
          "type" : "string" ,
          "required" : false
        } ,
        "return_url" : {
          "type" : "string" ,
          "required" : false
        } ,
        "cancel_url" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "create_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "update_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "links" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "href" : {
              "type" : "string" ,
              "required" : false
            } ,
            "rel" : {
              "type" : "string" ,
              "required" : false
            } ,
            "method" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== bobby-brennan/PayPal/examples/plan-example.json
{
  "id" : "P-8DY604244K970170GOALWR3I" ,
  "state" : "CREATED" ,
  "name" : "Fast Speed Plan" ,
  "description" : "Template creation." ,
  "type" : "FIXED" ,
  "payee" : {
    "merchant_id" : "1515831003405719294"
  } ,
  "payment_definitions" : [
    {
      "id" : "PD-8DY604244K970170GOALWR5Y" ,
      "name" : "Payment Definition-1" ,
      "type" : "REGULAR" ,
      "frequency" : "Month" ,
      "frequency_interval" : "2" ,
      "amount" : {
        "currency" : "USD" ,
        "value" : "100"
      } ,
      "cycles" : "12" ,
      "charge_models" : [
        {
          "id" : "CHM-8DY604244K970170GOALWR5Y" ,
          "type" : "SHIPPING" ,
          "amount" : {
            "currency" : "USD" ,
            "value" : "10"
          }
        } , {
          "id" : "CHM-0NJ10521L3680291SOALWR5Y" ,
          "type" : "TAX" ,
          "amount" : {
            "currency" : "USD" ,
            "value" : "12"
          }
        }
      ]
    }
  ] ,
  "merchant_preferences" : {
    "setup_fee" : {
      "currency" : "USD" ,
      "value" : "1"
    } ,
    "auto_bill_amount" : "YES" ,
    "initial_fail_amount_action" : "CONTINUE" ,
    "max_fail_attempts" : "0" ,
    "return_url" : "http://www.paypal.com" ,
    "cancel_url" : "http://www.yahoo.com"
  } ,
  "create_time" : "2014-06-06T07:32:00.877Z" ,
  "update_time" : "2014-06-06T07:32:00.877Z" ,
  "links" : [
    {
      "href" : "https://api.sandbox.paypal.com/v1/payments/billing-plans/P-8DY604244K970170GOALWR3I" ,
      "rel" : "self" ,
      "method" : "GET"
    }
  ]
}
