=== bobby-brennan/PayPal/schemas/refund-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "create_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "update_time" : {
      "type" : "string" ,
      "required" : false
    } ,
    "state" : {
      "type" : "string" ,
      "required" : false
    } ,
    "amount" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "total" : {
          "type" : "string" ,
          "required" : false
        } ,
        "currency" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "parent_payment" : {
      "type" : "string" ,
      "required" : false
    } ,
    "links" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "href" : {
              "type" : "string" ,
              "required" : false
            } ,
            "rel" : {
              "type" : "string" ,
              "required" : false
            } ,
            "method" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== bobby-brennan/PayPal/examples/authorization-example.json
{
  "id" : "6CR34526N64144512" ,
  "create_time" : "2013-05-06T21:56:50Z" ,
  "update_time" : "2013-05-06T21:57:51Z" ,
  "state" : "voided" ,
  "amount" : {
    "total" : "110.54" ,
    "currency" : "USD" ,
    "details" : {
      "subtotal" : "110.54"
    }
  } ,
  "parent_payment" : "PAY-0PL82432AD7432233KGECOIQ" ,
  "links" : [
    {
      "href" : "https://api.sandbox.paypal.com/v1/payments/authorization/6CR34526N64144512" ,
      "rel" : "self" ,
      "method" : "GET"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/payments/payment/PAY-0PL82432AD7432233KGECOIQ" ,
      "rel" : "parent_payment" ,
      "method" : "GET"
    }
  ]
}

=== bobby-brennan/PayPal/examples/sale-example.json
{
  "id" : "36C38912MN9658832" ,
  "create_time" : "2013-02-19T22:01:53Z" ,
  "update_time" : "2013-02-19T22:01:55Z" ,
  "state" : "completed" ,
  "amount" : {
    "total" : "7.47" ,
    "currency" : "USD"
  } ,
  "parent_payment" : "PAY-5YK922393D847794YKER7MUI" ,
  "links" : [
    {
      "href" : "https://api.sandbox.paypal.com/v1/payments/sale/36C38912MN9658832" ,
      "rel" : "self" ,
      "method" : "GET"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/payments/sale/36C38912MN9658832/refund" ,
      "rel" : "refund" ,
      "method" : "POST"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/payments/payment/PAY-5YK922393D847794YKER7MUI" ,
      "rel" : "parent_payment" ,
      "method" : "GET"
    }
  ]
}

=== bobby-brennan/PayPal/examples/refund-example.json
{
  "id" : "4CF18861HF410323U" ,
  "create_time" : "2013-01-31T04:13:34Z" ,
  "update_time" : "2013-01-31T04:13:36Z" ,
  "state" : "completed" ,
  "amount" : {
    "total" : "2.34" ,
    "currency" : "USD"
  } ,
  "parent_payment" : "PAY-46E69296BH2194803KEE662Y" ,
  "links" : [
    {
      "href" : "https://api.sandbox.paypal.com/v1/payments/refund/4CF18861HF410323U" ,
      "rel" : "self" ,
      "method" : "GET"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/payments/payment/PAY-46E69296BH2194803KEE662Y" ,
      "rel" : "parent_payment" ,
      "method" : "GET"
    } , {
      "href" : "https://api.sandbox.paypal.com/v1/payments/sale/2MU78835H4515710F" ,
      "rel" : "sale" ,
      "method" : "GET"
    }
  ]
}
